
criterion:
  name: ce

optimizer:
  name: adam
  lr: 0.002
  weight_decay: 0.0001

scheduler:
  name: cosine
  lr_gamma: 0.99
  lr_min: 0

run:
  experiment: "mnist_cnn_prune"
  n_epochs: 100
  batch_size: 32

quantize:
  weight_bit: 8
  input_bit: 8
  v_pi: 4.36
  v_max: 10.8

prune:
  topk: 4

morr:
  config: MORRConfig_20um_MQ
  trainable_bias: 0
  trainable_scale: 0
  morr_init: 1

checkpoint:
  save_best_model_k: 3
  checkpoint_dir: "mnist/cnn/prune"
  model_comment: ""
  resume: 0
  restore_checkpoint: ""
  no_linear: 0

model:
  name: "MORR_CLASS_CNN"

debug:
  verbose: 1

