dataset:
  name: mnist
  root: "./data"
  num_workers: 2
  img_height: 28
  img_width: 28
  in_channel: 1
  n_class: 10
  transform: basic
  shuffle: 0

criterion:
  name: ce

optimizer:
  name: adam
  lr: 0.002
  weight_decay: 0.0001

scheduler:
  name: cosine
  lr_gamma: 0.99
  lr_min: 0

run:
  experiment: "default"
  n_epochs: 100
  batch_size: 32
  use_cuda: 1
  gpu_id: 0
  deterministic: 1
  random_state: 42
  log_interval: 200
  train_noise: 0

quantize:
  weight_bit: 8
  input_bit: 8
  v_pi: 4.36
  v_max: 10.8

morr:
  config: MORRConfig_20um_MQ
  trainable_bias: 0
  trainable_scale: 0
  morr_init: 0

checkpoint:
  save_best_model_k: 3
  checkpoint_dir: "mnist/cnn/pretrain"
  model_comment: ""
  resume: 0
  restore_checkpoint: ""
  no_linear: 0

model:
  name: "MORR_CLASS_CNN"
  mode: "weight"
  kernel_list: [32, 32]
  kernel_size_list: [5, 5]
  hidden_list: []
  block_list: [8, 8, 4]
  stride_list: [2, 2]
  padding_list: [1, 1]
  pool_out_size: 5
  act: relu
  act_thres: 10
  norm: bn

debug:
  verbose: 1

